apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsm-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fsm-app
  template:
    metadata:
      labels:
        app: fsm-app
    spec:
      containers:
        - name: nextjs-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fsm-secrets
                  key: db_url
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: fsm-secrets
                  key: auth_secret

          # 🛡️ 1. Limites de ressources
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}

          # 🩺 2. Sonde de vivacité
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20

          # 🚦 3. Sonde de préparation
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10