version: "3.8"

services:
  # 1. La Base de Données (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: fsm-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      # Le fameux volume pour ne pas perdre les données !
      - db-data:/var/lib/postgresql/data
    networks:
      - fsm-network

  # 2. Ton application web (Next.js)
  web:
    build:
      context: ./web-admin
      dockerfile: Dockerfile
    container_name: fsm-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      # L'application se connecte au conteneur "db" grâce au réseau
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    networks:
      - fsm-network

# Déclaration du réseau interne
networks:
  fsm-network:
    driver: bridge

# Déclaration du volume persistant
volumes:
  db-data:
