version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: fsm_postgres_db
    restart: always
    environment:
      # On aligne avec votre code
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fsm_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web-admin:
    build:
      context: ./web-admin
      dockerfile: Dockerfile
    container_name: fsm_web_admin
    restart: always
    ports:
      - "3000:3000"
    environment:
      # L'hôte DOIT être "db" et non "localhost"
      - DATABASE_URL=postgresql://admin:admin@db:5432/fsm_db
      - NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.factice
    depends_on:
      - db

volumes:
  pgdata:
