apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: kube-prometheus-stack
    targetRevision: 58.2.2 # Version stable du chart
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring # On isole le monitoring dans son propre espace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Argo CD créera le namespace "monitoring" tout seul
